name: Test Coverage
on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.go'
  pull_request:
    paths:
      - 'src/**/*.go'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ "1.24.2" ]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Generate coverage report
        run: cd src && go test -v -coverprofile=profile.cov ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./src/profile.cov
          fail_ci_if_error: true
          verbose: true
