# Configuration - https://golangci-lint.run/
name: golangci-lint
on:
  push:
    branches: [main]
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"
permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m
          only-new-issues: true